# Generated by Django 2.0.1 on 2018-10-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_answer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='score',
        ),
    ]
